trigger: 
  - main

pool:
  vmImage: windows-2019

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: ValidateTerraform
        displayName: Validate Terraform
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'


