trigger: 
  - main

pool:
  vmImage: windows-2019

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: ValidateTerraform
        displayName: Validate Terraform
        steps:
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformTaskV2@2
            displayName: Init Terraform
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'dss-msdn'
              backendAzureRmKey: 'dss-msdn'
              backendAzureRmResourceGroupName: 'dss-devops-01'
              backendAzureRmStorageAccountName: 'dsstfstateeus01'
              backendAzureRmContainerName: 'tfstate'
              
          - task: TerraformTaskV2@2
            displayName: Validate Terraform
            inputs:
             command: validate


